name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Prepare pnpm via corepack
        run: corepack prepare pnpm@9.12.0 --activate

      - name: Setup pnpm action (redundant safety)
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm exec tsc --noEmit

      - name: Build
        run: pnpm run build

      - name: Ensure dist artifacts present
        run: test -f dist/index.js && test -f dist/index.mjs && test -f dist/index.d.ts || (echo 'expected build artifacts missing' && ls -R dist && exit 1)

      - name: Pack (dry run)
        run: pnpm pack --dry-run

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-dry-run
          path: |
            dist/**
            package.json
            README.md
            LICENSE
            *.tgz
